EarlyManApp/Controllers/CartController.cs
using AutoMapper;
using EarlyMan.Data;
using EarlyMan.Entities;
using EarlyMan.Entities.Identity;
using EarlyMan.Services;
using EarlyMan.ViewModels.CartViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EarlyMan.Controllers
{
    [Authorize(Roles ="Customer")]
    public class CartController : Controller
    {
        private readonly UserManager<ApplicationUser> _UserManager;
        private readonly ApplicationDbContext _Context;
        private readonly IProductRepository _ProductRepository;
        private readonly ICartRepository _CartRepository;
        private readonly ICartItemRepository _cartItemRepo;
        public int _pageSize = 10;
        
        public CartController(IMapper mapper,
            UserManager<ApplicationUser> userManager,
            ApplicationDbContext cxt,
            IProductRepository productRepository,
            ICartRepository cartRepository,
            ICartItemRepository cartItemRepository)
        {
            _UserManager = userManager;
            _Context = cxt;
            _ProductRepository = productRepository;
            _CartRepository = cartRepository;
            _cartItemRepo = cartItemRepository;
        }

       
        public IActionResult Index(int pageNumber = 0)
        {


            CartIndexViewModel cartIndexViewModel = new();

            // Get the currently signed in user's Id
            var userId = new Guid(HttpContext.User.Claims.FirstOrDefault
                (c => c.Type == ClaimTypes.NameIdentifier).Value);

            var userCart = _CartRepository.GetById(userId);

            List<CartItem> cartItems = new();
            

            // If user isn't blacklisted
            if (userCart.IsValid)
            {

                cartItems = _Context.CartItems
                    .Select(x => x)
                    .Where(x => x.CartId.ToString().ToLower() == userId.ToString().ToLower())
                    .Skip(pageNumber * _pageSize)
                    .Take(_pageSize)
                    .ToList();
            }


            // Create a cart view item for each item and then substract the available units from the product
            // quantity in the product repository.
            foreach (var cartItem in cartItems)
            {
                var product = _ProductRepository.GetProductById(cartItem.ProductId);

                CartViewItem cvItem = new()
                {
                    ImageLocation = product.ImageLocation,
                    ProductName = product.Name,
                    ProductDescription = product.Description,
                    ProductId = cartItem.ProductId,
                    CartItemId = cartItem.CartItemId,
                    PurchasePrice = cartItem.PurchasePrice,
                    PurchaseQuantity = cartItem.PurchaseQuantity,
                    SubTotal = cartItem.SubTotal,
                    
                };

                product.AvailableUnits -= cartItem.PurchaseQuantity;

                cartIndexViewModel.Items.Add(cvItem);
            }

            ViewData["ItemCount"] = _cartItemRepo.Count(userId);

            return View("Index" , cartIndexViewModel);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult AddToCart(Guid productId, int purchaseQuantity,
        decimal purchasePrice)
        {


            if (purchaseQuantity <= 0)
            {
                // pass validation error back to user
            }
            var userId = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            var userCart = _CartRepository.GetById(new Guid(userId));
           
            CartItem itemToCart = new()
            {
                CartItemId = Guid.NewGuid(),
                CartId = new Guid(userId),
                ProductId = productId,
                PurchaseQuantity = purchaseQuantity,
                PurchasePrice = purchasePrice,
                SubTotal = purchasePrice * purchaseQuantity,
                CreationDate = DateTime.Now,
                ModificationDate = DateTime.Now

            };

            userCart.IsValid = true;
            userCart.ModificationDate = DateTime.Now;
            userCart.Total += itemToCart.SubTotal;
           _cartItemRepo.Add(itemToCart);
           _Context.SaveChanges();

            return RedirectToAction("Index");

        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout()
        {
            var userId = new Guid(HttpContext.User.Claims.FirstOrDefault
               (c => c.Type == ClaimTypes.NameIdentifier).Value);

            _cartItemRepo.Checkout(userId);

            return RedirectToAction("Index");  
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveItem (Guid cartItemId)
        {
            _cartItemRepo.Remove(cartItemId);

            return RedirectToAction("Index");
        }
    }
}

EarlyManApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
</head>
<body>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

EarlyManApp/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="description" content="Affordable 3d printing" />
    <meta name="keywords" content="Artwork sale, EarlyMan, 3D printing, materials, PETA" />
    <meta name="author" content="David Okeke Chihurumnanya" />
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1" />

    <!-- Favicon -->
    <link href="favicon.ico" rel="icon" />
   
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,300;0,700;1,300&display=swap"
        rel="stylesheet">
    <!-- Icons -->

    <script src="https://kit.fontawesome.com/4405757738.js" crossorigin="anonymous"></script>    

    <!-- client-side libraries-->
    <link rel="stylesheet" href="/lib/normalize/normalize.min.css"/>
    
    <!-- Style sheets-->
    <link rel="stylesheet" href="/css/small.css" />
    <link rel="stylesheet" href="/css/medium.css" />
    <link rel="stylesheet" href="/css/large.css" />
    
    <!-- Page title-->
    <title>@ViewBag.Title</title>
</head>

<body>
    <!-- This website uses a 12-grid system -->
    
    <!-- .clear-fix -->
    <!-- Summary: Fixes height collapse of containers when decendants float left/right-->
    <header class="clear-fix">
      <div class="row limited">
        <section class="column small-12">
            <img src="/images/EarlyManLogo.svg" alt="Earlyman Logo">
            <h1>Earlyman</h1>
            <h2>Get You Local Art here...</h2>
        </section>
    </div> <!-- end row -->
    </header>

    
    <nav class="clear-fix">      
        <div class="row limited">         
             <button id="hamburgerBtn">&#9776;</button>              
             @(await Html.PartialAsync("_LoginPartial"))  
                 
        </div>
    </nav>

    <main class="clear-fix">
       @RenderBody()
    </main>

    <partial name="_CookieConsentPartial" />
    
    <footer class="clear-fix">
        <div class="row limited">
             @*
            <section class="column small-12 medium-6 large-3 ">

                <h2>Get to Know Us</h2>
                <ul>
                    <li>Make Money with Us</li>
                    <li>Let Us Help You</li>
                </ul>
            </section>

            <section class="column small-12 medium-6 large-3">
                <h2>Careers</h2>
                <ul>
                    <li>About Earlyman</li>
                    <li>Investor Relations</li>
                </ul>
            </section>
            <section class="column small-12 medium-6 large-3">
                <h2>Sell on Earlyman</h2>
                <ul>
                    <li>Become an Affiliate</li>
                    <li>Advertise Your Products</li>
                </ul>
            </section>*@
            <section class="container column small-12">
                <h2 class="text-white">Personal</h2>
                <ul>
                    <li><a asp-controller="UserAccount" asp-action="Index">Your Account</a></li>
                    <li><a asp-controller="Cart" asp-action"Index">Your Orders</a></li>
                    <li><a id="footer-help" href="mailto:davidokeke.c@gmail.com">Help</a></li>
                </ul>
            </section>

            <section class="column small-12 medium-6 large-3">
                <h2></h2>
                <img src="images/EarlyManLogo.svg" alt="logo" id="footer-img" />
                <p>&copy; 2022 &bull; all rights reserved.</p>
            </section>

        </div>
    </footer>

    <script src="~/js/toggle-menubar-for-small-screens.js"></script>
    

</body>
</html>